import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import AuthButton from "/components/AuthButton";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Campaign: Grave Mistake</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <AuthButton />
      </header>

      <main className={styles.main}>
        <h1 className={styles.title}>This Might Be a Grave Mistake</h1>

        <div className={styles.grid}>
          <div className={styles.card}>
            <Link href="/character">
              <a>See Your Character</a>
            </Link>
          </div>
          <div className={styles.card}>
            <Link href="/characters">
              <a>Current Characters</a>
            </Link>
          </div>
          <div className={styles.card}>
            <Link href="/history">
              <a>Brief History of Discworld</a>
            </Link>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>Jordan Renaud 2022</p>
      </footer>
    </div>
  );
}
