import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Campaign: Grave Mistake</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Campaign: Grave Mistake</h1>

        <div>
          <Link href="/character">
            <a>See your character</a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>Jordan Renaud 2022</p>
      </footer>
    </div>
  );
}
